version: '3.8'

services:
  app:
    image: pulse  
    container_name: frist-container
    ports:
      - "8080:80" 
    networks:
      - app-network
    restart: always

  # MySQL Database container
  mysql:
    image: mysql:latest  
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw 
      MYSQL_DATABASE: mydb  
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql  
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local

